#!/usr/bin/env python3
# Author: Radoslaw Kubera (rkubera on GitHub).
# SPDX-License-Identifier: MIT
"""Compress portal CSS/JavaScript deterministically using Python's standard library."""
import argparse
import gzip
import re
from control_assets import segments, selected, emit_profile_chunks, emit_chunks
from pathlib import Path


def portal_parts(root, ota=True, mqtt=True, console=True, controls=None, guarded=False, tls=True):
    """Return the selected UI; excluded HTML and JS are absent from its asset."""
    source = (root / 'PortalPage.h').read_text(encoding='utf-8')
    body = source.split('R"HTML(', 1)[1].split(')HTML"', 1)[0]
    for enabled, ids in [(ota, ['upgrade']), (mqtt, ['mqtt']), (console, ['console'])]:
        if not enabled:
            for section in ids:
                body = re.sub(r'<section id="' + section + r'"[\s\S]*?</section>', '', body)
    body=re.sub(r'/\*@if ARDPORTAL_ENABLE_MQTT_TLS\*/(.*?)/\*@endif\*/',lambda m:m[1] if tls and mqtt else '',body,flags=re.S)
    css = re.search(r'<style>(.*?)</style>', body, re.S).group(1)
    script = re.search(r'<script>(.*?)</script>', body, re.S).group(1)
    for enabled, entry in [(ota, 'upgrade'), (mqtt, 'mqtt'), (console, 'console')]:
        if not enabled:
            script = re.sub(r",?\{id:'" + entry + r"',path:'[^']+',label:'[^']+'\}", '', script)
    if not ota:
        script = '\n'.join(line for line in script.split('\n')
                           if not line.startswith("document.querySelector('#upgradeForm').onsubmit")
                           and not line.startswith("document.querySelector('#upgradeUrlForm').onsubmit"))
    if not console:
        script = script.replace("else document.querySelector('#publishForm').elements.topic.placeholder=t('ui_097',{device:document.title})", "")
        script = script.replace("document.querySelector('#publishForm').elements.topic.placeholder=t('ui_097',{device:c.deviceName});", "")
        script = script.replace("if(currentPage?.id==='console')setMessage(document.querySelector('#consoleState'),consoleErrorKey?t(consoleErrorKey):'',!!consoleErrorKey);", "")
        script = script.replace("const consoleRows={mqtt:[]};", "")
        script = re.sub(r"^function consoleAvailability\(\).*?$", 'function consoleAvailability(){}', script, flags=re.M)
        script = '\n'.join(line for line in script.split('\n')
                           if not line.startswith("document.querySelector('#publishForm').onsubmit")
                           and line != "if(currentPage?.id==='console')consoleAvailability();")
        script = script.replace("setMessage(document.querySelector('#consoleState'),", "setConsoleMessage(")
        script = script.replace("function openConsole()", "function setConsoleMessage(){}\nfunction openConsole()")
        script = script.replace("currentPage?.id==='console'?'/api/console':'/api/events'", "'/api/events'")
        # Only application value/status notifications remain in the WebSocket receiver.
        start = script.index("else if(message.type==='log'")
        end = script.index("}catch(error)", start)
        script = script[:start] + script[end:]
    if not mqtt:
        script = script.replace("mqttForm=document.querySelector('#mqttForm')", "mqttForm=null")
        script = '\n'.join(line for line in script.split('\n')
                           if not line.startswith('function setCaVisibility')
                           and not line.startswith('mqttForm.elements.mqttTls.onchange'))
        script = script.replace('setCaVisibility()', '')
    script_block = re.search(r'<script>(.*?)</script>', body, re.S)
    selected_body = body[:script_block.start()] + '<script>' + script + '</script>' + body[script_block.end():]
    shell = selected_body.replace('<style>' + css + '</style>', '<link rel="stylesheet" href="/portal.css">')
    shell = shell.replace('<script>' + script + '</script>', '<script src="/portal.js"></script>')
    return (css, script, shell) if guarded else (selected(css, controls), selected(script, controls), shell)


def gzip_array(name, text):
    data = bytearray(gzip.compress(text.encode('utf-8'), compresslevel=9, mtime=0))
    data[9] = 255
    lines = ['static const char ' + name + '[] PROGMEM =']
    for offset in range(0, len(data), 32):
        lines.append('"' + ''.join('\\x%02x' % byte for byte in data[offset:offset + 32]) + '"')
    lines[-1] += ';'
    return lines


def generate(root):
    lines = ['// Author: Radoslaw Kubera (rkubera on GitHub).', '// SPDX-License-Identifier: MIT',
             '// Generated by tools/generate_portal_assets.py. Edit PortalPage.h instead.',
             '#pragma once', '#include <Arduino.h>', '#include "ArdPortalFeatures.h"', '#include "ArdAsset.h"']
    css, _, _ = portal_parts(root, guarded=True)
    lines += emit_profile_chunks('PORTAL_CSS_GZIP', css, gzip_array)
    variants = [(1, 1, 1), (1, 1, 0), (1, 0, 0), (0, 1, 1), (0, 1, 0), (0, 0, 0)]
    variants=[(*flags,tls) for flags in variants for tls in ([1,0] if flags[1] else [0])]
    for index, (ota, mqtt, console, tls) in enumerate(variants):
        flags = [('OTA', ota), ('MQTT', mqtt), ('CONSOLE', console), ('MQTT_TLS',tls)]
        condition = ' && '.join(('' if value else '!') + 'ARDPORTAL_ENABLE_' + name for name, value in flags)
        lines.append(('#if ' if not index else '#elif ') + condition)
        _, script, shell = portal_parts(root, ota, mqtt, console, guarded=True,tls=tls)
        head=(root/'PortalPage.h').read_text().split('R"HEAD(',1)[1].split(')HEAD"',1)[0].split('<script id="pageCatalog"',1)[0]
        minimal=head+shell.removeprefix('</script>')
        minimal=re.sub(r'<section id="dynamicLoading".*?</section>','',minimal,flags=re.S)
        minimal=re.sub(r'<nav id="dynamicNavigation".*?</nav>','',minimal,flags=re.S)
        lines += ['#if ARDPORTAL_ENABLE_DYNAMIC_PAGES','static const char PORTAL_HTML[] PROGMEM = R"ASSET(' + shell + ')ASSET";','#else']
        lines += emit_chunks('PORTAL_HTML_GZIP',[('1',minimal)],gzip_array)
        lines += ['#endif']
        lines += emit_profile_chunks('PORTAL_JS_GZIP', script, gzip_array)
    lines += ['#else', '#error Invalid ArdPortal UI feature combination', '#endif']
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = root / 'PortalAssets.h'
    output = generate(root)
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != output:
            raise SystemExit('PortalAssets.h is stale; run tools/generate_portal_assets.py')
    else:
        target.write_text(output, encoding='utf-8')


if __name__ == '__main__':
    main()
