// Author: Radoslaw Kubera (rkubera on GitHub).
// SPDX-License-Identifier: MIT
#pragma once
#include <Arduino.h>

// Define options before including ArdPortal.h in the main sketch.
// Unspecified modules are enabled by default.
#ifndef ARDPORTAL_ENABLE_DYNAMIC_PAGES
#define ARDPORTAL_ENABLE_DYNAMIC_PAGES 1
#endif
#if ARDPORTAL_ENABLE_DYNAMIC_PAGES != 0 && ARDPORTAL_ENABLE_DYNAMIC_PAGES != 1
#error ARDPORTAL_ENABLE_DYNAMIC_PAGES must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_DEPENDENCIES
#define ARDPORTAL_ENABLE_DEPENDENCIES 1
#endif
#if ARDPORTAL_ENABLE_DEPENDENCIES != 0 && ARDPORTAL_ENABLE_DEPENDENCIES != 1
#error ARDPORTAL_ENABLE_DEPENDENCIES must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_OTA
#define ARDPORTAL_ENABLE_OTA 1
#endif
#ifndef ARDPORTAL_ENABLE_MQTT
#define ARDPORTAL_ENABLE_MQTT 1
#endif
#ifndef ARDPORTAL_ENABLE_MQTT_TLS
#define ARDPORTAL_ENABLE_MQTT_TLS 1
#endif
#if ARDPORTAL_ENABLE_MQTT_TLS != 0 && ARDPORTAL_ENABLE_MQTT_TLS != 1
#error ARDPORTAL_ENABLE_MQTT_TLS must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONSOLE
#define ARDPORTAL_ENABLE_CONSOLE 1
#endif
#ifndef ARDPORTAL_ENABLE_CONSOLE_MESSAGES
#define ARDPORTAL_ENABLE_CONSOLE_MESSAGES 0
#endif
#if ARDPORTAL_ENABLE_CONSOLE_MESSAGES != 0 && ARDPORTAL_ENABLE_CONSOLE_MESSAGES != 1
#error ARDPORTAL_ENABLE_CONSOLE_MESSAGES must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_HA
#define ARDPORTAL_ENABLE_HA 1
#endif
#if (ARDPORTAL_ENABLE_OTA != 0 && ARDPORTAL_ENABLE_OTA != 1) ||     (ARDPORTAL_ENABLE_MQTT != 0 && ARDPORTAL_ENABLE_MQTT != 1) ||     (ARDPORTAL_ENABLE_HA != 0 && ARDPORTAL_ENABLE_HA != 1) || (ARDPORTAL_ENABLE_CONSOLE != 0 && ARDPORTAL_ENABLE_CONSOLE != 1)
#error ArdPortal feature flags must be 0 or 1
#endif
#if !ARDPORTAL_ENABLE_MQTT
#undef ARDPORTAL_ENABLE_MQTT_TLS
#define ARDPORTAL_ENABLE_MQTT_TLS 0
#undef ARDPORTAL_ENABLE_HA
#define ARDPORTAL_ENABLE_HA 0
#undef ARDPORTAL_ENABLE_CONSOLE
#define ARDPORTAL_ENABLE_CONSOLE 0
#endif
#if !ARDPORTAL_ENABLE_CONSOLE
#undef ARDPORTAL_ENABLE_CONSOLE_MESSAGES
#define ARDPORTAL_ENABLE_CONSOLE_MESSAGES 0
#endif
#if !ARDPORTAL_ENABLE_DYNAMIC_PAGES
#undef ARDPORTAL_ENABLE_HA
#define ARDPORTAL_ENABLE_HA 0
#undef ARDPORTAL_ENABLE_DEPENDENCIES
#define ARDPORTAL_ENABLE_DEPENDENCIES 0
#endif
#define ARDPORTAL_SUPPORT_WEBSOCKET (ARDPORTAL_ENABLE_DYNAMIC_PAGES || ARDPORTAL_ENABLE_CONSOLE)
// The constructor signature detects mismatched settings in additional source files.
template<uint64_t Features> struct ArdPortalBuildTag {};

#if !ARDPORTAL_ENABLE_DYNAMIC_PAGES
#undef ARDPORTAL_ENABLE_CONTROL_SLIDER
#define ARDPORTAL_ENABLE_CONTROL_SLIDER 0
#undef ARDPORTAL_ENABLE_CONTROL_TEXT
#define ARDPORTAL_ENABLE_CONTROL_TEXT 0
#undef ARDPORTAL_ENABLE_CONTROL_SELECT
#define ARDPORTAL_ENABLE_CONTROL_SELECT 0
#undef ARDPORTAL_ENABLE_CONTROL_EDIT
#define ARDPORTAL_ENABLE_CONTROL_EDIT 0
#undef ARDPORTAL_ENABLE_CONTROL_SWITCH
#define ARDPORTAL_ENABLE_CONTROL_SWITCH 0
#undef ARDPORTAL_ENABLE_CONTROL_CLIMATE
#define ARDPORTAL_ENABLE_CONTROL_CLIMATE 0
#undef ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR
#define ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR 0
#undef ARDPORTAL_ENABLE_CONTROL_DATE
#define ARDPORTAL_ENABLE_CONTROL_DATE 0
#undef ARDPORTAL_ENABLE_CONTROL_TIME
#define ARDPORTAL_ENABLE_CONTROL_TIME 0
#undef ARDPORTAL_ENABLE_CONTROL_DATETIME
#define ARDPORTAL_ENABLE_CONTROL_DATETIME 0
#undef ARDPORTAL_ENABLE_CONTROL_BUTTON
#define ARDPORTAL_ENABLE_CONTROL_BUTTON 0
#undef ARDPORTAL_ENABLE_CONTROL_SCENE
#define ARDPORTAL_ENABLE_CONTROL_SCENE 0
#undef ARDPORTAL_ENABLE_CONTROL_NOTIFY
#define ARDPORTAL_ENABLE_CONTROL_NOTIFY 0
#undef ARDPORTAL_ENABLE_CONTROL_INFRARED
#define ARDPORTAL_ENABLE_CONTROL_INFRARED 0
#undef ARDPORTAL_ENABLE_CONTROL_EVENT
#define ARDPORTAL_ENABLE_CONTROL_EVENT 0
#undef ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER
#define ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER 0
#undef ARDPORTAL_ENABLE_CONTROL_TAG
#define ARDPORTAL_ENABLE_CONTROL_TAG 0
#undef ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER
#define ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER 0
#undef ARDPORTAL_ENABLE_CONTROL_LIGHT
#define ARDPORTAL_ENABLE_CONTROL_LIGHT 0
#undef ARDPORTAL_ENABLE_CONTROL_FAN
#define ARDPORTAL_ENABLE_CONTROL_FAN 0
#undef ARDPORTAL_ENABLE_CONTROL_COVER
#define ARDPORTAL_ENABLE_CONTROL_COVER 0
#undef ARDPORTAL_ENABLE_CONTROL_VALVE
#define ARDPORTAL_ENABLE_CONTROL_VALVE 0
#undef ARDPORTAL_ENABLE_CONTROL_LOCK
#define ARDPORTAL_ENABLE_CONTROL_LOCK 0
#undef ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL
#define ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL 0
#undef ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER
#define ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER 0
#undef ARDPORTAL_ENABLE_CONTROL_SIREN
#define ARDPORTAL_ENABLE_CONTROL_SIREN 0
#undef ARDPORTAL_ENABLE_CONTROL_VACUUM
#define ARDPORTAL_ENABLE_CONTROL_VACUUM 0
#undef ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER
#define ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER 0
#undef ARDPORTAL_ENABLE_CONTROL_WATER_HEATER
#define ARDPORTAL_ENABLE_CONTROL_WATER_HEATER 0
#undef ARDPORTAL_ENABLE_CONTROL_UPDATE
#define ARDPORTAL_ENABLE_CONTROL_UPDATE 0
#endif
// Dynamic field types: override any flag before including ArdPortal.h.
#ifndef ARDPORTAL_ENABLE_CONTROLS
#define ARDPORTAL_ENABLE_CONTROLS 1
#endif
#if ARDPORTAL_ENABLE_CONTROLS != 0 && ARDPORTAL_ENABLE_CONTROLS != 1
#error ARDPORTAL_ENABLE_CONTROLS must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_SLIDER
#define ARDPORTAL_ENABLE_CONTROL_SLIDER ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_SLIDER != 0 && ARDPORTAL_ENABLE_CONTROL_SLIDER != 1
#error ARDPORTAL_ENABLE_CONTROL_SLIDER must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_TEXT
#define ARDPORTAL_ENABLE_CONTROL_TEXT ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_TEXT != 0 && ARDPORTAL_ENABLE_CONTROL_TEXT != 1
#error ARDPORTAL_ENABLE_CONTROL_TEXT must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_SELECT
#define ARDPORTAL_ENABLE_CONTROL_SELECT ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_SELECT != 0 && ARDPORTAL_ENABLE_CONTROL_SELECT != 1
#error ARDPORTAL_ENABLE_CONTROL_SELECT must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_EDIT
#define ARDPORTAL_ENABLE_CONTROL_EDIT ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_EDIT != 0 && ARDPORTAL_ENABLE_CONTROL_EDIT != 1
#error ARDPORTAL_ENABLE_CONTROL_EDIT must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_SWITCH
#define ARDPORTAL_ENABLE_CONTROL_SWITCH ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_SWITCH != 0 && ARDPORTAL_ENABLE_CONTROL_SWITCH != 1
#error ARDPORTAL_ENABLE_CONTROL_SWITCH must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_CLIMATE
#define ARDPORTAL_ENABLE_CONTROL_CLIMATE ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_CLIMATE != 0 && ARDPORTAL_ENABLE_CONTROL_CLIMATE != 1
#error ARDPORTAL_ENABLE_CONTROL_CLIMATE must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR
#define ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR != 0 && ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR != 1
#error ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_DATE
#define ARDPORTAL_ENABLE_CONTROL_DATE ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_DATE != 0 && ARDPORTAL_ENABLE_CONTROL_DATE != 1
#error ARDPORTAL_ENABLE_CONTROL_DATE must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_TIME
#define ARDPORTAL_ENABLE_CONTROL_TIME ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_TIME != 0 && ARDPORTAL_ENABLE_CONTROL_TIME != 1
#error ARDPORTAL_ENABLE_CONTROL_TIME must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_DATETIME
#define ARDPORTAL_ENABLE_CONTROL_DATETIME ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_DATETIME != 0 && ARDPORTAL_ENABLE_CONTROL_DATETIME != 1
#error ARDPORTAL_ENABLE_CONTROL_DATETIME must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_BUTTON
#define ARDPORTAL_ENABLE_CONTROL_BUTTON ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_BUTTON != 0 && ARDPORTAL_ENABLE_CONTROL_BUTTON != 1
#error ARDPORTAL_ENABLE_CONTROL_BUTTON must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_SCENE
#define ARDPORTAL_ENABLE_CONTROL_SCENE ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_SCENE != 0 && ARDPORTAL_ENABLE_CONTROL_SCENE != 1
#error ARDPORTAL_ENABLE_CONTROL_SCENE must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_NOTIFY
#define ARDPORTAL_ENABLE_CONTROL_NOTIFY ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_NOTIFY != 0 && ARDPORTAL_ENABLE_CONTROL_NOTIFY != 1
#error ARDPORTAL_ENABLE_CONTROL_NOTIFY must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_INFRARED
#define ARDPORTAL_ENABLE_CONTROL_INFRARED ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_INFRARED != 0 && ARDPORTAL_ENABLE_CONTROL_INFRARED != 1
#error ARDPORTAL_ENABLE_CONTROL_INFRARED must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_EVENT
#define ARDPORTAL_ENABLE_CONTROL_EVENT ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_EVENT != 0 && ARDPORTAL_ENABLE_CONTROL_EVENT != 1
#error ARDPORTAL_ENABLE_CONTROL_EVENT must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER
#define ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER != 0 && ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER != 1
#error ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_TAG
#define ARDPORTAL_ENABLE_CONTROL_TAG ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_TAG != 0 && ARDPORTAL_ENABLE_CONTROL_TAG != 1
#error ARDPORTAL_ENABLE_CONTROL_TAG must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER
#define ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER != 0 && ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER != 1
#error ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_LIGHT
#define ARDPORTAL_ENABLE_CONTROL_LIGHT ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_LIGHT != 0 && ARDPORTAL_ENABLE_CONTROL_LIGHT != 1
#error ARDPORTAL_ENABLE_CONTROL_LIGHT must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_FAN
#define ARDPORTAL_ENABLE_CONTROL_FAN ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_FAN != 0 && ARDPORTAL_ENABLE_CONTROL_FAN != 1
#error ARDPORTAL_ENABLE_CONTROL_FAN must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_COVER
#define ARDPORTAL_ENABLE_CONTROL_COVER ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_COVER != 0 && ARDPORTAL_ENABLE_CONTROL_COVER != 1
#error ARDPORTAL_ENABLE_CONTROL_COVER must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_VALVE
#define ARDPORTAL_ENABLE_CONTROL_VALVE ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_VALVE != 0 && ARDPORTAL_ENABLE_CONTROL_VALVE != 1
#error ARDPORTAL_ENABLE_CONTROL_VALVE must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_LOCK
#define ARDPORTAL_ENABLE_CONTROL_LOCK ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_LOCK != 0 && ARDPORTAL_ENABLE_CONTROL_LOCK != 1
#error ARDPORTAL_ENABLE_CONTROL_LOCK must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL
#define ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL != 0 && ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL != 1
#error ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER
#define ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER != 0 && ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER != 1
#error ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_SIREN
#define ARDPORTAL_ENABLE_CONTROL_SIREN ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_SIREN != 0 && ARDPORTAL_ENABLE_CONTROL_SIREN != 1
#error ARDPORTAL_ENABLE_CONTROL_SIREN must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_VACUUM
#define ARDPORTAL_ENABLE_CONTROL_VACUUM ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_VACUUM != 0 && ARDPORTAL_ENABLE_CONTROL_VACUUM != 1
#error ARDPORTAL_ENABLE_CONTROL_VACUUM must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER
#define ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER != 0 && ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER != 1
#error ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_WATER_HEATER
#define ARDPORTAL_ENABLE_CONTROL_WATER_HEATER ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_WATER_HEATER != 0 && ARDPORTAL_ENABLE_CONTROL_WATER_HEATER != 1
#error ARDPORTAL_ENABLE_CONTROL_WATER_HEATER must be 0 or 1
#endif
#ifndef ARDPORTAL_ENABLE_CONTROL_UPDATE
#define ARDPORTAL_ENABLE_CONTROL_UPDATE ARDPORTAL_ENABLE_CONTROLS
#endif
#if ARDPORTAL_ENABLE_CONTROL_UPDATE != 0 && ARDPORTAL_ENABLE_CONTROL_UPDATE != 1
#error ARDPORTAL_ENABLE_CONTROL_UPDATE must be 0 or 1
#endif
#define ARDPORTAL_CONTROL_SUPPORT_EXTENDED (ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR || ARDPORTAL_ENABLE_CONTROL_DATE || ARDPORTAL_ENABLE_CONTROL_TIME || ARDPORTAL_ENABLE_CONTROL_DATETIME || ARDPORTAL_ENABLE_CONTROL_BUTTON || ARDPORTAL_ENABLE_CONTROL_SCENE || ARDPORTAL_ENABLE_CONTROL_NOTIFY || ARDPORTAL_ENABLE_CONTROL_INFRARED || ARDPORTAL_ENABLE_CONTROL_EVENT || ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER || ARDPORTAL_ENABLE_CONTROL_TAG || ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER || ARDPORTAL_ENABLE_CONTROL_LIGHT || ARDPORTAL_ENABLE_CONTROL_FAN || ARDPORTAL_ENABLE_CONTROL_COVER || ARDPORTAL_ENABLE_CONTROL_VALVE || ARDPORTAL_ENABLE_CONTROL_LOCK || ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL || ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER || ARDPORTAL_ENABLE_CONTROL_SIREN || ARDPORTAL_ENABLE_CONTROL_VACUUM || ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER || ARDPORTAL_ENABLE_CONTROL_WATER_HEATER || ARDPORTAL_ENABLE_CONTROL_UPDATE)
#define ARDPORTAL_CONTROL_SUPPORT_DIAL (ARDPORTAL_ENABLE_CONTROL_CLIMATE || ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER || ARDPORTAL_ENABLE_CONTROL_WATER_HEATER)
#define ARDPORTAL_CONTROL_SUPPORT_SWITCH (ARDPORTAL_ENABLE_CONTROL_SWITCH || ARDPORTAL_ENABLE_CONTROL_LIGHT || ARDPORTAL_ENABLE_CONTROL_FAN || ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER || ARDPORTAL_ENABLE_CONTROL_SIREN)
#define ARDPORTAL_CONTROL_SUPPORT_SLIDER (ARDPORTAL_ENABLE_CONTROL_SLIDER || ARDPORTAL_ENABLE_CONTROL_LIGHT || ARDPORTAL_ENABLE_CONTROL_FAN || ARDPORTAL_ENABLE_CONTROL_COVER || ARDPORTAL_ENABLE_CONTROL_VALVE || ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER || ARDPORTAL_ENABLE_CONTROL_SIREN || ARDPORTAL_ENABLE_CONTROL_WATER_HEATER)
#define ARDPORTAL_CONTROL_SUPPORT_SELECT (ARDPORTAL_ENABLE_CONTROL_SELECT || ARDPORTAL_ENABLE_CONTROL_CLIMATE || ARDPORTAL_ENABLE_CONTROL_FAN || ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER || ARDPORTAL_ENABLE_CONTROL_SIREN || ARDPORTAL_ENABLE_CONTROL_WATER_HEATER || ARDPORTAL_ENABLE_CONTROL_VACUUM)
#define ARDPORTAL_CONTROL_SUPPORT_ACTIONS (ARDPORTAL_ENABLE_CONTROL_BUTTON || ARDPORTAL_ENABLE_CONTROL_SCENE || ARDPORTAL_ENABLE_CONTROL_NOTIFY || ARDPORTAL_ENABLE_CONTROL_INFRARED || ARDPORTAL_ENABLE_CONTROL_COVER || ARDPORTAL_ENABLE_CONTROL_VALVE || ARDPORTAL_ENABLE_CONTROL_LOCK || ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL || ARDPORTAL_ENABLE_CONTROL_VACUUM || ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER || ARDPORTAL_ENABLE_CONTROL_UPDATE)
#define ARDPORTAL_CONTROL_SUPPORT_GROUPED_ACTIONS (ARDPORTAL_ENABLE_CONTROL_COVER || ARDPORTAL_ENABLE_CONTROL_VALVE || ARDPORTAL_ENABLE_CONTROL_LOCK || ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL || ARDPORTAL_ENABLE_CONTROL_VACUUM || ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER)

/**
 * @brief Check whether a basic control type is enabled in this build.
 * @param type JSON, control or protocol type being examined.
 * @return True if a basic control type is enabled in this build; false otherwise.
 */
inline bool ardPortalBasicControl(const String& type) {
#if ARDPORTAL_ENABLE_CONTROL_SLIDER
  if(type=="slider") return true;
#endif
#if ARDPORTAL_ENABLE_CONTROL_TEXT
  if(type=="text") return true;
#endif
#if ARDPORTAL_ENABLE_CONTROL_SELECT
  if(type=="select") return true;
#endif
#if ARDPORTAL_ENABLE_CONTROL_EDIT
  if(type=="edit") return true;
#endif
#if ARDPORTAL_ENABLE_CONTROL_SWITCH
  if(type=="switch") return true;
#endif
#if ARDPORTAL_ENABLE_CONTROL_CLIMATE
  if(type=="climate") return true;
#endif
  (void)type; return false;
}

// Include field selection in the cross-translation-unit settings check.
#undef ARDPORTAL_FEATURE_MASK
#define ARDPORTAL_FEATURE_MASK ((uint64_t(ARDPORTAL_ENABLE_CONSOLE_MESSAGES) << 37) | (uint64_t(ARDPORTAL_ENABLE_MQTT_TLS) << 36) | (uint64_t(ARDPORTAL_ENABLE_DYNAMIC_PAGES) << 35) | (uint64_t(ARDPORTAL_ENABLE_DEPENDENCIES) << 10) | uint64_t(ARDPORTAL_ENABLE_OTA) | (uint64_t(ARDPORTAL_ENABLE_MQTT) << 1) | (uint64_t(ARDPORTAL_ENABLE_HA) << 2) | (uint64_t(ARDPORTAL_ENABLE_CONSOLE) << 3) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_SLIDER) << 4) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_TEXT) << 5) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_SELECT) << 6) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_EDIT) << 7) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_SWITCH) << 8) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_CLIMATE) << 9) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR) << 11) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_DATE) << 12) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_TIME) << 13) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_DATETIME) << 14) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_BUTTON) << 15) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_SCENE) << 16) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_NOTIFY) << 17) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_INFRARED) << 18) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_EVENT) << 19) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER) << 20) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_TAG) << 21) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER) << 22) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_LIGHT) << 23) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_FAN) << 24) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_COVER) << 25) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_VALVE) << 26) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_LOCK) << 27) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL) << 28) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER) << 29) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_SIREN) << 30) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_VACUUM) << 31) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER) << 32) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_WATER_HEATER) << 33) | (uint64_t(ARDPORTAL_ENABLE_CONTROL_UPDATE) << 34))

// Common profiles can use a single gzip member for maximum compression.
#define ARDPORTAL_CONTROL_PROFILE_FULL (ARDPORTAL_ENABLE_CONTROL_SLIDER && ARDPORTAL_ENABLE_CONTROL_TEXT && ARDPORTAL_ENABLE_CONTROL_SELECT && ARDPORTAL_ENABLE_CONTROL_EDIT && ARDPORTAL_ENABLE_CONTROL_SWITCH && ARDPORTAL_ENABLE_CONTROL_CLIMATE && ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR && ARDPORTAL_ENABLE_CONTROL_DATE && ARDPORTAL_ENABLE_CONTROL_TIME && ARDPORTAL_ENABLE_CONTROL_DATETIME && ARDPORTAL_ENABLE_CONTROL_BUTTON && ARDPORTAL_ENABLE_CONTROL_SCENE && ARDPORTAL_ENABLE_CONTROL_NOTIFY && ARDPORTAL_ENABLE_CONTROL_INFRARED && ARDPORTAL_ENABLE_CONTROL_EVENT && ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER && ARDPORTAL_ENABLE_CONTROL_TAG && ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER && ARDPORTAL_ENABLE_CONTROL_LIGHT && ARDPORTAL_ENABLE_CONTROL_FAN && ARDPORTAL_ENABLE_CONTROL_COVER && ARDPORTAL_ENABLE_CONTROL_VALVE && ARDPORTAL_ENABLE_CONTROL_LOCK && ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL && ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER && ARDPORTAL_ENABLE_CONTROL_SIREN && ARDPORTAL_ENABLE_CONTROL_VACUUM && ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER && ARDPORTAL_ENABLE_CONTROL_WATER_HEATER && ARDPORTAL_ENABLE_CONTROL_UPDATE)
#define ARDPORTAL_CONTROL_PROFILE_BASIC (ARDPORTAL_ENABLE_CONTROL_SLIDER && ARDPORTAL_ENABLE_CONTROL_TEXT && ARDPORTAL_ENABLE_CONTROL_SELECT && ARDPORTAL_ENABLE_CONTROL_EDIT && !ARDPORTAL_ENABLE_CONTROL_SWITCH && !ARDPORTAL_ENABLE_CONTROL_CLIMATE && !ARDPORTAL_ENABLE_CONTROL_BINARY_SENSOR && !ARDPORTAL_ENABLE_CONTROL_DATE && !ARDPORTAL_ENABLE_CONTROL_TIME && !ARDPORTAL_ENABLE_CONTROL_DATETIME && !ARDPORTAL_ENABLE_CONTROL_BUTTON && !ARDPORTAL_ENABLE_CONTROL_SCENE && !ARDPORTAL_ENABLE_CONTROL_NOTIFY && !ARDPORTAL_ENABLE_CONTROL_INFRARED && !ARDPORTAL_ENABLE_CONTROL_EVENT && !ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER && !ARDPORTAL_ENABLE_CONTROL_TAG && !ARDPORTAL_ENABLE_CONTROL_DEVICE_TRACKER && !ARDPORTAL_ENABLE_CONTROL_LIGHT && !ARDPORTAL_ENABLE_CONTROL_FAN && !ARDPORTAL_ENABLE_CONTROL_COVER && !ARDPORTAL_ENABLE_CONTROL_VALVE && !ARDPORTAL_ENABLE_CONTROL_LOCK && !ARDPORTAL_ENABLE_CONTROL_ALARM_CONTROL_PANEL && !ARDPORTAL_ENABLE_CONTROL_HUMIDIFIER && !ARDPORTAL_ENABLE_CONTROL_SIREN && !ARDPORTAL_ENABLE_CONTROL_VACUUM && !ARDPORTAL_ENABLE_CONTROL_LAWN_MOWER && !ARDPORTAL_ENABLE_CONTROL_WATER_HEATER && !ARDPORTAL_ENABLE_CONTROL_UPDATE)

#define ARDPORTAL_CONTROL_SUPPORT_EVENTS (ARDPORTAL_ENABLE_CONTROL_EVENT || ARDPORTAL_ENABLE_CONTROL_DEVICE_TRIGGER || ARDPORTAL_ENABLE_CONTROL_TAG)
#define ARDPORTAL_CONTROL_SUPPORT_EMISSIONS (ARDPORTAL_CONTROL_SUPPORT_ACTIONS || ARDPORTAL_CONTROL_SUPPORT_EVENTS)
