#!/usr/bin/env python3
"""Generate Unicode Letter/Number ranges for device-name validation."""
import unicodedata
from pathlib import Path
ranges=[]
for cp in range(128,0x110000):
    if unicodedata.category(chr(cp))[0] in 'LN':
        if ranges and ranges[-1][1]+1==cp:ranges[-1][1]=cp
        else:ranges.append([cp,cp])
text='// Generated by tools/generate_device_name_characters.py.\n#pragma once\n#include <Arduino.h>\n#include <stdint.h>\nnamespace ArdDeviceName {\nstatic const uint32_t Characters[][2] PROGMEM = {\n'
text+=''.join('  {0x%x,0x%x},\n'%tuple(r) for r in ranges)
text+='};\n}\n'
(Path(__file__).resolve().parents[1]/'DeviceNameCharacters.h').write_text(text)
